### ISSUE TITLE
ImportError: No module named multiprocessing.pool

### ISSUE THREAD

**Issue by NoelOConnell** [kiddac/E2_Piconizer#1]
Hi,

Attached is a crash report for when I tried running this plugin.
I have OpenATV 6.4 on Zgemma H7s. It's a fresh install, I followed your OpenATV setup guide and removed the extensions suggested.

Python version : 2.7.16

I worked around the error by using OpenWebif and running the `dependencies.sh` file manually in the terminal.
The plugin ran correctly then.

Just highlighting it here in case it helps others.

[enigma2_crash_1601225607.log](https://github.com/kiddac/E2_Piconizer/files/5300814/enigma2_crash_1601225607.log)

**Comment by dfgsaerh** [comment]
Having the exact same error. Thanks for posting the workaround

**Comment by kiddac** [comment]
Files have been updated to fix dependency check and make it compatible with python 3.9 images. i.e openatv 7 and openvix 6.
